// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4nQRLbp8v0QEYulxic31pyUtztgJmYk',
    appId: '1:680298750372:web:c0bc395153974aae15e131',
    messagingSenderId: '680298750372',
    projectId: 'koffiloop',
    authDomain: 'koffiloop.firebaseapp.com',
    storageBucket: 'koffiloop.firebasestorage.app',
    measurementId: 'G-MCCKPYRBBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlbNcKkkAjnCBDoBkDeckphG1io_GykI',
    appId: '1:680298750372:android:aed3646f872ac64e15e131',
    messagingSenderId: '680298750372',
    projectId: 'koffiloop',
    storageBucket: 'koffiloop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ENywKekSCx7cfJpXxiOefFlZVJaSQQ4',
    appId: '1:680298750372:ios:44514822192172c715e131',
    messagingSenderId: '680298750372',
    projectId: 'koffiloop',
    storageBucket: 'koffiloop.firebasestorage.app',
    iosBundleId: 'com.example.koffiloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ENywKekSCx7cfJpXxiOefFlZVJaSQQ4',
    appId: '1:680298750372:ios:44514822192172c715e131',
    messagingSenderId: '680298750372',
    projectId: 'koffiloop',
    storageBucket: 'koffiloop.firebasestorage.app',
    iosBundleId: 'com.example.koffiloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4nQRLbp8v0QEYulxic31pyUtztgJmYk',
    appId: '1:680298750372:web:74ac2769dc01f06015e131',
    messagingSenderId: '680298750372',
    projectId: 'koffiloop',
    authDomain: 'koffiloop.firebaseapp.com',
    storageBucket: 'koffiloop.firebasestorage.app',
    measurementId: 'G-511K3J3828',
  );
}
